### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by Gerynant24** [stevenewey/octograph#13]
I'm trying follow the installation steps with a Raspi2 but when I try to run **docker-compose up -d** I am getting
**ERROR: no matching manifest for linux/arm/v7 in the manifest list entries**

Any idea what I'm doing wrong please?

**Comment by stevenewey** [comment]
You're not doing anything wrong. I hadn't locked down the version of InfluxDB which I use to store the collected data, and the most recent versions don't support 32-bit ARM. I've updated the `docker-compose.yml` file now to lock it to an older version. Hopefully this will resolve it for you.
