### ISSUE TITLE
Consumption units for gas

### ISSUE THREAD

**Issue by bendoswell** [stevenewey/octograph#8]
Depending on the smart meter type, the unit of measurements are:
SMETS1 Secure gas meters: kWh
SMETS2 gas meters: m^3

Comparing the dashboard with my bill, the gas consumption on grafana is in kwh (**24kwh**), but looking at my bill, the actual consumption was volumetric: **24m^3** which equated to 264kwh of energy. 

![Screenshot 2020-06-13 at 17 37 46](https://user-images.githubusercontent.com/47357635/84574172-a00e0c00-ad9c-11ea-8797-7b0ee240cd99.png)
![Screenshot 2020-06-13 at 17 37 11](https://user-images.githubusercontent.com/47357635/84574173-a0a6a280-ad9c-11ea-8b94-488f3701df01.png)

**Comment by amertner** [comment]
That is correct - I am working on a fix for this.

**Comment by optiz0r** [comment]
Had a stab at implementing this myself. Only had consumptuon data for a day myself, so not enough to compare against a real bill to confirm I got it right.
